# Generated by Django 5.1.2 on 2024-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя в телеграмме"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="ID телеграмм аккаунта"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_last_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Фамилия в телеграмме",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тег в телеграмме"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Почта"
            ),
        ),
    ]
