# Generated by Django 5.1.2 on 2024-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_first_name_user_tg_id_user_tg_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен"
            ),
        ),
    ]
