# Generated by Django 5.2.7 on 2025-10-21 11:37

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


def ensure_links(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    link_model = apps.get_model("users", "UserPersonLink")
    for user in user_model.objects.all():
        link_model.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0022_alter_family_contact_person_and_more"),
        ("users", "0004_user_is_approved_person_family"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="family",
        ),
        migrations.AddField(
            model_name="user",
            name="first_bot_interaction_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Первое взаимодействие с ботом"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_bot_interaction_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее взаимодействие с ботом"
            ),
        ),
        migrations.CreateModel(
            name="UserPersonLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_reasons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Причины совпадения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("approved", "Связь подтверждена"),
                            ("rejected", "Связь отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус решения",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата решения"
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(
                        blank=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "user_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий пользователя"
                    ),
                ),
                (
                    "user_comment_updated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Комментарий пользователя обновлён",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_link_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Решение принял",
                    ),
                ),
                (
                    "suggested_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_user_links",
                        to="school.person",
                        verbose_name="Предложенная персона",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предварительная связь пользователя и персоны",
                "verbose_name_plural": "Предварительные связи пользователей и персон",
            },
        ),
        migrations.RunPython(ensure_links, migrations.RunPython.noop),
    ]
