services:
  web:
    build: .
    command: sh -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  bot:
    build: .
    command: poetry run python tg_bot/bot.py
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - web
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  celery_worker:
    build: .
    command: poetry run celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery_beat:
    build: .
    command: poetry run celery -A config beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

volumes:
  redis_data:

volumes:
  static_volume:
