# Generated by Django 5.2.7 on 2025-10-16 19:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0018_class_coach_comment_class_coach_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=90, verbose_name="Продолжительность (мин.)"
                    ),
                ),
                (
                    "season_start_month",
                    models.PositiveSmallIntegerField(
                        help_text="1 — январь, 12 — декабрь",
                        verbose_name="Месяц начала сезона",
                    ),
                ),
                (
                    "season_end_month",
                    models.PositiveSmallIntegerField(
                        help_text="1 — январь, 12 — декабрь",
                        verbose_name="Месяц окончания сезона",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("fitness", "ОФП"),
                            ("rollers", "Ролики"),
                            ("ice", "Коньки"),
                            ("ski", "Лыжи"),
                            ("ski_beginners", "Лыжи (начинающие)"),
                            ("ski_drills", "Упражнения (лыжи)"),
                            ("slalom", "Слалом"),
                            ("giant_slalom", "Гигантский слалом"),
                            ("bike", "Велотренировка"),
                            ("skitech", "Тренажер SkiTech"),
                            ("other", "Уточняется"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Вид тренировки",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("murinsky_park", "Муринский парк"),
                            ("utc_kavgolovo", "УТЦ Кавголово"),
                            ("yukki", "Юкки"),
                            ("snezny", "Снежный"),
                            ("serverny_slope", "Серверный склон"),
                            ("other", "Локация уточняется"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Локация",
                    ),
                ),
                (
                    "equipment",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("athletic", "Спортивная одежда, кроссовки"),
                                ("rollers", "Ролики, защита"),
                                ("skates", "Коньки, защита"),
                                ("bike", "Велосипед, защита"),
                                ("slalom_ski", "Слаломные лыжи, защита"),
                                ("gs_ski", "Лыжи для гигантского слалома, защита"),
                                ("other", "Уточняется"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Экипировка",
                    ),
                ),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("regular", "Регулярное"),
                            ("individual", "Индивидуальное"),
                            ("camp", "В ходе сбора"),
                        ],
                        default="regular",
                        max_length=10,
                        verbose_name="Тип занятия",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_templates",
                        to="school.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон занятия",
                "verbose_name_plural": "Шаблоны занятий",
                "ordering": ("group__name", "day_of_week", "start_time"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "group",
                            "day_of_week",
                            "start_time",
                            "season_start_month",
                            "season_end_month",
                        ),
                        name="classes_trainingtemplate_unique_slot",
                    )
                ],
            },
        ),
    ]
