# Generated by Django 5.2.7 on 2025-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_seed_training_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingtemplate",
            name="training_type",
            field=models.CharField(
                choices=[
                    ("fitness", "ОФП"),
                    ("rollers", "Ролики"),
                    ("ice", "Коньки"),
                    ("ski", "Лыжи"),
                    ("ski_beginners", "Лыжи (начинающие)"),
                    ("ski_drills", "Упражнения (лыжи)"),
                    ("slalom", "Слалом"),
                    ("giant_slalom", "Гигантский слалом"),
                    ("bike", "Велотренировка"),
                    ("skitech", "Тренажер SkiTech"),
                    ("trampoline", "Батут"),
                    ("manezh", "Манеж"),
                    ("other", "Уточняется"),
                ],
                default="other",
                max_length=32,
                verbose_name="Вид тренировки",
            ),
        ),
    ]
