# Generated by Django 5.2.7 on 2025-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_trainingtemplate_training_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingtemplate",
            name="location",
            field=models.CharField(
                choices=[
                    ("murinsky_park", "Муринский парк"),
                    ("utc_kavgolovo", "УТЦ Кавголово"),
                    ("yukki", "Юкки"),
                    ("snezny", "Снежный"),
                    ("serverny_slope", "Серверный склон"),
                    ("okhta_park", "Охта парк"),
                    ("other", "Локация уточняется"),
                ],
                default="other",
                max_length=32,
                verbose_name="Локация",
            ),
        ),
    ]
