# Generated by Django 5.2.7 on 2025-10-23 12:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_trainingtemplate_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingtemplate",
            name="equipment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("athletic", "Спортивная одежда, кроссовки"),
                        ("rollers", "Ролики, защита"),
                        ("skates", "Коньки, защита"),
                        ("ice", "Коньки"),
                        ("bike", "Велосипед, защита"),
                        ("slalom_ski", "Слаломные лыжи, защита"),
                        ("gs_ski", "Лыжи для гигантского слалома, защита"),
                        ("other", "Уточняется"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Экипировка",
            ),
        ),
    ]
