# Generated by Django 6.0.2 on 2026-03-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_id", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=255)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("payload_json", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payload_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
    ]
