# Generated by Django 6.0.2 on 2026-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_streamrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamrun",
            name="protocol_link",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
    ]
