# Generated by Django 5.1.2 on 2024-11-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(max_length=50, verbose_name="Уровень подготовки"),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Разряд"
                    ),
                ),
                (
                    "medical_certificate",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Справка-допуск",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Спортсмен",
                "verbose_name_plural": "Спортсмены",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата и время занятия")),
                (
                    "duration",
                    models.IntegerField(
                        verbose_name="Продолжительность занятия (мин.)"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Место проведения"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("regular", "Регулярное"),
                            ("individual", "Индивидуальное"),
                            ("camp", "В ходе сбора"),
                        ],
                        max_length=10,
                        verbose_name="Тип занятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название соревнования"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Место проведения"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание соревнования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family_name",
                    models.CharField(max_length=100, verbose_name="Фамилия семьи"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Семья",
                "verbose_name_plural": "Семьи",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "middlename",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Telegram"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=6,
                        verbose_name="Пол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Человек",
                "verbose_name_plural": "Люди",
            },
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to="school.athlete",
                        verbose_name="Спортсмен",
                    ),
                ),
                (
                    "class_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="school.class",
                        verbose_name="Занятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на занятие",
                "verbose_name_plural": "Записи на занятия",
            },
        ),
        migrations.CreateModel(
            name="CompetitionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(max_length=100, verbose_name="Результат участия"),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_entries",
                        to="school.athlete",
                        verbose_name="Спортсмен",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="school.competition",
                        verbose_name="Соревнование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в соревнованиях",
                "verbose_name_plural": "Участия в соревнованиях",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название группы"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Уровень подготовки",
                    ),
                ),
                (
                    "coaches",
                    models.ManyToManyField(
                        related_name="groups", to="school.coach", verbose_name="Тренеры"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="school.group",
                verbose_name="Группа",
            ),
        ),
        migrations.CreateModel(
            name="GroupMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_enrollments",
                        to="school.athlete",
                        verbose_name="Спортсмен",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="school.group",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спортсмен группы",
                "verbose_name_plural": "Спортсмены группы",
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.CharField(max_length=50, verbose_name="Отношение")),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="school.family",
                        verbose_name="Семья",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.person",
                        verbose_name="Человек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Член семьи",
                "verbose_name_plural": "Члены семьи",
            },
        ),
        migrations.AddField(
            model_name="family",
            name="contact_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to="school.person",
                verbose_name="Контактное лицо",
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.person",
                verbose_name="Человек",
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.person",
                verbose_name="Человек",
            ),
        ),
        migrations.CreateModel(
            name="PotentialClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interested_in", models.TextField(verbose_name="Интересующие услуги")),
                (
                    "source",
                    models.CharField(max_length=100, verbose_name="Откуда узнал"),
                ),
                (
                    "trial_lesson",
                    models.BooleanField(
                        default=False, verbose_name="Запись на пробное занятие"
                    ),
                ),
                (
                    "first_month_paid",
                    models.BooleanField(
                        default=False, verbose_name="Оплатил первый месяц"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.person",
                        verbose_name="Человек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Потенциальный клиент",
                "verbose_name_plural": "Потенциальные клиенты",
            },
        ),
        migrations.CreateModel(
            name="TrainingCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала сбора")),
                ("end_date", models.DateField(verbose_name="Дата окончания сбора")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Место проведения"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание сбора"
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        related_name="camps", to="school.class", verbose_name="Занятия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Спортивный сбор",
                "verbose_name_plural": "Спортивные сборы",
            },
        ),
        migrations.CreateModel(
            name="CampEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_start",
                    models.DateTimeField(verbose_name="Дата и время начала участия"),
                ),
                (
                    "attendance_end",
                    models.DateTimeField(verbose_name="Дата и время окончания участия"),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camp_enrollments",
                        to="school.athlete",
                        verbose_name="Спортсмен",
                    ),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="school.trainingcamp",
                        verbose_name="Сбор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в сборах",
                "verbose_name_plural": "Участия в сборах",
            },
        ),
    ]
