# Generated by Django 5.1.2 on 2024-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="level",
            field=models.CharField(
                choices=[
                    ("2015-2016", "2015/2016"),
                    ("2016-2017", "2016/2017"),
                    ("2017-2018", "2017/2018"),
                    ("2018-2019", "2018/2019"),
                    ("2019-2020", "2019/2020"),
                    ("2020-2021", "2020/2021"),
                    ("2021-2022", "2021/2022"),
                    ("2022-2023", "2022/2023"),
                    ("2023-2024", "2023/2024"),
                    ("2024-2025", "2024/2025"),
                ],
                max_length=50,
                verbose_name="Уровень подготовки (Первый сезон)",
            ),
        ),
    ]
