# Generated by Django 5.1.2 on 2024-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_athlete_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(default="1970-01-01", verbose_name="Дата рождения"),
        ),
    ]
