# Generated by Django 5.1.2 on 2024-11-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_person_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["surname"],
                "verbose_name": "Человек",
                "verbose_name_plural": "Люди",
            },
        ),
    ]
