# Generated by Django 5.1.2 on 2024-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="family_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия семьи"
            ),
        ),
    ]
