# Generated by Django 5.1.2 on 2024-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_alter_family_family_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="family_name",
            field=models.CharField(
                blank=True,
                help_text="Заполнится автоматически",
                max_length=100,
                null=True,
                verbose_name="Фамилия семьи",
            ),
        ),
    ]
