# Generated by Django 5.1.2 on 2024-11-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_alter_family_family_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="relation",
            field=models.CharField(
                choices=[
                    ("mother", "Мать"),
                    ("father", "Отец"),
                    ("son", "Сын"),
                    ("daughter", "Дочь"),
                    ("grandfather", "Дед"),
                    ("grandmother", "Бабушка"),
                    ("representative", "Представитель"),
                    ("guardian", "Опекун"),
                    ("grandson", "Внук"),
                    ("granddaughter", "Внучка"),
                ],
                max_length=50,
                verbose_name="Отношение",
            ),
        ),
    ]
