# Generated by Django 5.1.2 on 2024-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_group_athletes_alter_group_coaches_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="athletes",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups_athletes",
                to="school.athlete",
                verbose_name="Спортсмены",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="coaches",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                to="school.coach",
                verbose_name="Тренеры",
            ),
        ),
    ]
