# Generated by Django 5.1.2 on 2024-11-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0009_alter_group_athletes_alter_group_coaches"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athlete",
            options={
                "ordering": ["person__surname"],
                "verbose_name": "Спортсмен",
                "verbose_name_plural": "Спортсмены",
            },
        ),
    ]
