# Generated by Django 5.1.2 on 2024-11-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_alter_trainingcamp_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcamp",
            name="classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="camps",
                to="school.class",
                verbose_name="Занятия",
            ),
        ),
    ]
