# Generated by Django 5.1.2 on 2025-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0012_alter_trainingcamp_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="classenrollment",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Подтверждено"),
        ),
    ]
