# Generated by Django 5.1.2 on 2025-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0013_classenrollment_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="person/photos", verbose_name="Фото"
            ),
        ),
    ]
