# Generated by Django 5.2.7 on 2025-10-16 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0016_contracts"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="class",
            name="equipment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Список экипировки, можно выбрать несколько вариантов",
                size=None,
                verbose_name="Необходимое снаряжение",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="training_type",
            field=models.CharField(
                default="уточняется",
                help_text="Например ОФП, ролики или другое направление из списка",
                max_length=100,
                verbose_name="Вид тренировки",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="location",
            field=models.CharField(
                default="Локация уточняется",
                help_text="Ключевое место тренировки, например из предложенного списка",
                max_length=100,
                verbose_name="Место проведения",
            ),
        ),
    ]
