# Generated by Django 5.2.7 on 2025-10-16 19:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0017_class_comment_class_equipment_class_training_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="coach_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий тренера"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="coach_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("planned", "Запланировано"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус у тренера",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="coach_status_set_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Обработано тренером"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="creation_source",
            field=models.CharField(
                choices=[
                    ("manual", "Создано вручную"),
                    ("template", "Создано автоматически по шаблону"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Источник создания",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="equipment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("athletic", "Спортивная одежда, кроссовки"),
                        ("rollers", "Ролики, защита"),
                        ("skates", "Коньки, защита"),
                        ("bike", "Велосипед, защита"),
                        ("slalom_ski", "Слаломные лыжи, защита"),
                        ("gs_ski", "Лыжи для гигантского слалома, защита"),
                        ("other", "Уточняется"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="Список экипировки, можно выбрать несколько вариантов",
                size=None,
                verbose_name="Необходимое снаряжение",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="location",
            field=models.CharField(
                choices=[
                    ("murinsky_park", "Муринский парк"),
                    ("utc_kavgolovo", "УТЦ Кавголово"),
                    ("yukki", "Юкки"),
                    ("snezny", "Снежный"),
                    ("serverny_slope", "Серверный склон"),
                    ("other", "Локация уточняется"),
                ],
                default="other",
                help_text="Ключевое место тренировки, например из предложенного списка",
                max_length=32,
                verbose_name="Место проведения",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="training_type",
            field=models.CharField(
                choices=[
                    ("fitness", "ОФП"),
                    ("rollers", "Ролики"),
                    ("ice", "Коньки"),
                    ("ski", "Лыжи"),
                    ("ski_beginners", "Лыжи (начинающие)"),
                    ("ski_drills", "Упражнения (лыжи)"),
                    ("slalom", "Слалом"),
                    ("giant_slalom", "Гигантский слалом"),
                    ("bike", "Велотренировка"),
                    ("skitech", "Тренажер SkiTech"),
                    ("other", "Уточняется"),
                ],
                default="other",
                help_text="Например ОФП, ролики или другое направление из списка",
                max_length=32,
                verbose_name="Вид тренировки",
            ),
        ),
    ]
