# Generated by Codex
from django.db import migrations
from django.utils import timezone

from school.choices import (
    ClassCoachStatus,
    TrainingEquipment,
    TrainingKind,
    TrainingLocation,
)


def normalize_class_fields(apps, schema_editor):
    Class = apps.get_model("school", "Class")

    kind_values = {value for value, _ in TrainingKind.choices}
    location_values = {value for value, _ in TrainingLocation.choices}
    equipment_values = {value for value, _ in TrainingEquipment.choices}

    kind_by_label = {label.lower(): value for value, label in TrainingKind.choices}
    location_by_label = {label.lower(): value for value, label in TrainingLocation.choices}
    equipment_by_label = {label.lower(): value for value, label in TrainingEquipment.choices}
    equipment_by_label["спортивная одежда, кросовки"] = TrainingEquipment.ATHLETIC
    equipment_by_label["уточняется"] = TrainingEquipment.OTHER

    now = timezone.now()

    for class_instance in Class.objects.all():
        update_fields: list[str] = []

        raw_training = (class_instance.training_type or "").lower().strip()
        if class_instance.training_type not in kind_values:
            new_kind = kind_by_label.get(raw_training, TrainingKind.OTHER)
            if class_instance.training_type != new_kind:
                class_instance.training_type = new_kind
                update_fields.append("training_type")

        raw_location = (class_instance.location or "").lower().strip()
        if class_instance.location not in location_values:
            new_location = location_by_label.get(raw_location, TrainingLocation.OTHER)
            if class_instance.location != new_location:
                class_instance.location = new_location
                update_fields.append("location")

        equipment_list = list(class_instance.equipment or [])
        mapped_equipment: list[str] = []
        for item in equipment_list:
            if item in equipment_values:
                mapped_equipment.append(item)
            else:
                normalized = (item or "").lower().strip()
                mapped_equipment.append(equipment_by_label.get(normalized, TrainingEquipment.OTHER))
        if mapped_equipment != equipment_list:
            class_instance.equipment = mapped_equipment
            update_fields.append("equipment")

        if class_instance.creation_source == "manual" and class_instance.coach_status != ClassCoachStatus.PLANNED:
            class_instance.coach_status = ClassCoachStatus.PLANNED
            class_instance.coach_status_set_at = now
            update_fields.extend(["coach_status", "coach_status_set_at"])

        if update_fields:
            class_instance.save(update_fields=list(set(update_fields)))


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0018_class_coach_comment_class_coach_status_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_class_fields, migrations.RunPython.noop),
    ]
