# Generated by Django 5.2.7 on 2025-10-16 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0019_class_data_normalization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="level",
            field=models.CharField(
                choices=[
                    ("2015-2016", "2015/2016"),
                    ("2016-2017", "2016/2017"),
                    ("2017-2018", "2017/2018"),
                    ("2018-2019", "2018/2019"),
                    ("2019-2020", "2019/2020"),
                    ("2020-2021", "2020/2021"),
                    ("2021-2022", "2021/2022"),
                    ("2022-2023", "2022/2023"),
                    ("2023-2024", "2023/2024"),
                    ("2024-2025", "2024/2025"),
                    ("2025-2026", "2025/2026"),
                ],
                max_length=50,
                verbose_name="Уровень подготовки (Первый сезон)",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to="school.person",
                verbose_name="Контактное лицо",
            ),
        ),
    ]
