# Generated by Django 5.2.7 on 2025-10-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0021_remove_family_pricing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="families",
                to="school.person",
                verbose_name="Контактное лицо",
            ),
        ),
        migrations.AlterField(
            model_name="familymember",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.person",
                verbose_name="Человек",
            ),
        ),
    ]
