# Generated by Django 5.2.7 on 2025-10-21 15:17

from django.db import migrations, models


def clear_placeholder_birthdays(apps, schema_editor):
    Person = apps.get_model("school", "Person")
    Person.objects.filter(date_of_birth="1970-01-01").update(date_of_birth=None)


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0022_alter_family_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.RunPython(clear_placeholder_birthdays, migrations.RunPython.noop),
    ]
