# Generated by Django 5.2.7 on 2025-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0024_class_assistant_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="assistant_comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Комментарий ассистента"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="training_type",
            field=models.CharField(
                choices=[
                    ("fitness", "ОФП"),
                    ("rollers", "Ролики"),
                    ("ice", "Коньки"),
                    ("ski", "Лыжи"),
                    ("ski_beginners", "Лыжи (начинающие)"),
                    ("ski_drills", "Упражнения (лыжи)"),
                    ("slalom", "Слалом"),
                    ("giant_slalom", "Гигантский слалом"),
                    ("bike", "Велотренировка"),
                    ("skitech", "Тренажер SkiTech"),
                    ("trampoline", "Батут"),
                    ("manezh", "Манеж"),
                    ("other", "Уточняется"),
                ],
                default="other",
                help_text="Например ОФП, ролики или другое направление из списка",
                max_length=32,
                verbose_name="Вид тренировки",
            ),
        ),
        migrations.AlterField(
            model_name="classenrollment",
            name="assistant_comment",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Комментарий ассистента",
            ),
        ),
        migrations.AlterField(
            model_name="familymember",
            name="relation",
            field=models.CharField(
                choices=[
                    ("mother", "Мама"),
                    ("father", "Папа"),
                    ("son", "Сын"),
                    ("daughter", "Дочь"),
                    ("grandfather", "Дедушка"),
                    ("grandmother", "Бабушка"),
                    ("representative", "Представитель"),
                    ("guardian", "Опекун"),
                    ("grandson", "Внук"),
                    ("granddaughter", "Внучка"),
                ],
                max_length=50,
                verbose_name="Отношение",
            ),
        ),
    ]
