# Generated by Django 5.2.7 on 2025-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0026_alter_class_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="location",
            field=models.CharField(
                choices=[
                    ("murinsky_park", "Муринский парк"),
                    ("utc_kavgolovo", "УТЦ Кавголово"),
                    ("yukki", "Юкки"),
                    ("snezny", "Снежный"),
                    ("serverny_slope", "Серверный склон"),
                    ("okhta_park", "Охта парк"),
                    ("park_house", "Бугры (ТЦ Парк хаус)"),
                    ("sever_park", "Север парк арена (Руставели 38)"),
                    ("other", "Локация уточняется"),
                ],
                default="other",
                help_text="Ключевое место тренировки, например из предложенного списка",
                max_length=32,
                verbose_name="Место проведения",
            ),
        ),
    ]
