# Generated by Django 5.2.7 on 2025-10-23 15:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0028_alter_class_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="equipment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("athletic", "Спортивная одежда, кроссовки"),
                        ("rollers", "Ролики, защита"),
                        ("skates", "Коньки, защита"),
                        ("ice", "Коньки"),
                        ("ski_boots", "Горнолыжные ботинки"),
                        ("bike", "Велосипед, защита"),
                        ("slalom_ski", "Слаломные лыжи, защита"),
                        ("gs_ski", "Лыжи для гигантского слалома, защита"),
                        ("other", "Уточняется"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="Список экипировки, можно выбрать несколько вариантов",
                size=None,
                verbose_name="Необходимое снаряжение",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="school.group",
                verbose_name="Группа",
            ),
        ),
    ]
