# Generated by Django 6.0.2 on 2026-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0034_competition_applications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="level",
            field=models.CharField(
                choices=[
                    ("unknown", "Не указан"),
                    ("2015-2016", "2015/2016"),
                    ("2016-2017", "2016/2017"),
                    ("2017-2018", "2017/2018"),
                    ("2018-2019", "2018/2019"),
                    ("2019-2020", "2019/2020"),
                    ("2020-2021", "2020/2021"),
                    ("2021-2022", "2021/2022"),
                    ("2022-2023", "2022/2023"),
                    ("2023-2024", "2023/2024"),
                    ("2024-2025", "2024/2025"),
                    ("2025-2026", "2025/2026"),
                ],
                max_length=50,
                verbose_name="Уровень подготовки (Первый сезон)",
            ),
        ),
    ]
