# Generated by Django 6.0.2 on 2026-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0035_alter_athlete_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("БР", "БР"),
                    ("3ю", "3ю"),
                    ("2ю", "2ю"),
                    ("1ю", "1ю"),
                    ("III", "III"),
                    ("II", "II"),
                    ("I", "I"),
                    ("КМС", "КМС"),
                    ("МС", "МС"),
                    ("МСМК", "МСМК"),
                ],
                max_length=50,
                null=True,
                verbose_name="Разряд",
            ),
        ),
    ]
