# Generated by Django 6.0.2 on 2026-02-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_competition_competition_type_competition_discipline"),
        ("school", "0037_kanaev_applications"),
    ]

    operations = []
