# Generated by Django 6.0.2 on 2026-02-22 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0041_alter_competition_birth_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("ok", "Успешно"),
                            ("partial", "Частично"),
                            ("error", "Ошибка"),
                            ("failed_validation", "Ошибка валидации"),
                            ("failed_openai", "Ошибка AI"),
                            ("failed_download", "Ошибка загрузки документа"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="Статус анализа",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Request ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("competition_general", "Соревнование (общий)"),
                            ("athlete_specific", "Спортсмен (личный)"),
                            ("other", "Другое"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Тип документа AI",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Уверенность"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "extracted",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Нормализованные данные"
                    ),
                ),
                (
                    "issues",
                    models.JSONField(blank=True, default=list, verbose_name="Проблемы"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ"
                    ),
                ),
                (
                    "error_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("download", "Загрузка"),
                            ("openai", "AI"),
                            ("validation", "Валидация"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Стадия ошибки",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст ошибки"
                    ),
                ),
                (
                    "source_persistent_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        verbose_name="Постоянный URL источника",
                    ),
                ),
                (
                    "source_signed_url_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash signed URL"
                    ),
                ),
                (
                    "is_analyzed_successfully",
                    models.BooleanField(
                        default=False, verbose_name="Успешно проанализирован"
                    ),
                ),
                (
                    "document_updated_at_snapshot",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Снимок updated_at документа",
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время анализа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "AI-анализ документа",
                "verbose_name_plural": "AI-анализ документов",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AddIndex(
            model_name="athletedocument",
            index=models.Index(
                fields=["athlete", "doc_type"], name="school_athl_athlete_84ae2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="athletedocument",
            index=models.Index(
                fields=["document"], name="school_athl_documen_f11f94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competitiondocument",
            index=models.Index(
                fields=["competition", "doc_type"],
                name="school_comp_competi_148039_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="competitiondocument",
            index=models.Index(
                fields=["document"], name="school_comp_documen_4a43d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="school_docu_created_1da98a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["updated_at"], name="school_docu_updated_ae60db_idx"
            ),
        ),
        migrations.AddField(
            model_name="documentaianalysis",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_analysis",
                to="school.document",
                verbose_name="Документ",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(fields=["status"], name="school_docu_status_b07566_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(
                fields=["doc_type"], name="school_docu_doc_typ_b8b757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(
                fields=["is_analyzed_successfully"],
                name="school_docu_is_anal_f178d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(
                fields=["analyzed_at"], name="school_docu_analyze_2cd13c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(
                fields=["document_updated_at_snapshot"],
                name="school_docu_documen_895927_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(
                fields=["request_id"], name="school_docu_request_2b3a12_idx"
            ),
        ),
    ]
