# Generated by Django 6.0.2 on 2026-02-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0042_documentaianalysis_document_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentaianalysis",
            name="auto_bound",
            field=models.BooleanField(
                default=False, verbose_name="Автопривязка выполнена"
            ),
        ),
        migrations.AddField(
            model_name="documentaianalysis",
            name="bound_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время привязки"
            ),
        ),
        migrations.AddField(
            model_name="documentaianalysis",
            name="bound_entity_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="ID связанной сущности"
            ),
        ),
        migrations.AddField(
            model_name="documentaianalysis",
            name="bound_entity_type",
            field=models.CharField(
                blank=True,
                help_text="competition | athlete",
                max_length=20,
                null=True,
                verbose_name="Тип связанной сущности",
            ),
        ),
        migrations.AlterField(
            model_name="athletedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("regulation", "Регламент/Положение"),
                    ("schedule", "Расписание/Распорядок"),
                    ("start_list", "Стартовый лист"),
                    ("start_list_second", "Стартовый лист второй попытки"),
                    ("intermediate_results", "Промежуточные результаты"),
                    ("prelim_results", "Результаты предварительные"),
                    ("official_results", "Результаты официальные"),
                    ("application_form", "Форма заявки"),
                    ("parent_consent", "Согласие родителей"),
                    ("medical_certificate", "Медицинская справка"),
                    ("insurance", "Страховка"),
                    ("passport", "Паспорт"),
                    ("birth_certificate", "Свидетельство о рождении"),
                    ("rank_book", "Разрядная книжка"),
                    ("rusada_certificate", "Сертификат РУСАДА"),
                    ("other", "Прочее"),
                ],
                max_length=50,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="competitiondocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("regulation", "Регламент/Положение"),
                    ("schedule", "Расписание/Распорядок"),
                    ("start_list", "Стартовый лист"),
                    ("start_list_second", "Стартовый лист второй попытки"),
                    ("intermediate_results", "Промежуточные результаты"),
                    ("prelim_results", "Результаты предварительные"),
                    ("official_results", "Результаты официальные"),
                    ("application_form", "Форма заявки"),
                    ("parent_consent", "Согласие родителей"),
                    ("medical_certificate", "Медицинская справка"),
                    ("insurance", "Страховка"),
                    ("passport", "Паспорт"),
                    ("birth_certificate", "Свидетельство о рождении"),
                    ("rank_book", "Разрядная книжка"),
                    ("rusada_certificate", "Сертификат РУСАДА"),
                    ("other", "Прочее"),
                ],
                max_length=50,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaianalysis",
            index=models.Index(
                fields=["bound_entity_type", "bound_entity_id"],
                name="school_docu_bound_e_b08505_idx",
            ),
        ),
    ]
