# Generated by Django 6.0.2 on 2026-02-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0043_documentaianalysis_auto_bound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="SHA256 хеш содержимого",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["size", "content_hash"], name="school_docu_size_1f4e55_idx"
            ),
        ),
    ]
