# Generated by Django 6.0.2 on 2026-02-22 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0044_document_content_hash_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAIJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус job",
                    ),
                ),
                (
                    "force",
                    models.BooleanField(
                        default=False, verbose_name="Принудительный анализ"
                    ),
                ),
                (
                    "total_documents",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Документов в job"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст ошибки job"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало обработки"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание обработки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем создано",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job документов",
                "verbose_name_plural": "AI jobs документов",
            },
        ),
        migrations.CreateModel(
            name="DocumentAIJobItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус документа в job",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Request ID батча"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст ошибки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_job_items",
                        to="school.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="school.documentaijob",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI job item документа",
                "verbose_name_plural": "AI job items документов",
            },
        ),
        migrations.AddIndex(
            model_name="documentaijob",
            index=models.Index(fields=["status"], name="school_docu_status_05e7d6_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaijob",
            index=models.Index(
                fields=["created_at"], name="school_docu_created_e4646b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaijob",
            index=models.Index(
                fields=["updated_at"], name="school_docu_updated_789eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaijobitem",
            index=models.Index(
                fields=["job", "status"], name="school_docu_job_id_3556cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaijobitem",
            index=models.Index(
                fields=["document"], name="school_docu_documen_cb785a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaijobitem",
            index=models.Index(
                fields=["updated_at"], name="school_docu_updated_e26657_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentaijobitem",
            constraint=models.UniqueConstraint(
                fields=("job", "document"), name="uniq_ai_job_item_job_document"
            ),
        ),
    ]
