# Generated by Django 6.0.2 on 2026-03-01 19:58

import django.db.models.deletion
import re
import school.models
from django.db import migrations, models


def _normalize_location_name(value: str | None) -> str:
    if not value:
        return ""
    normalized = value.lower().strip().replace("ё", "е")
    return re.sub(r"[^\w\dа-я]+", "", normalized)


def forwards_fill_competition_venues(apps, schema_editor):
    Competition = apps.get_model("school", "Competition")
    CompetitionVenue = apps.get_model("school", "CompetitionVenue")

    venues_by_norm = {}
    for venue in CompetitionVenue.objects.all().only("id", "short_name"):
        norm = _normalize_location_name(venue.short_name)
        if norm:
            venues_by_norm.setdefault(norm, venue)

    for competition in Competition.objects.all().only("id", "location").iterator():
        raw_name = (competition.location or "").strip()
        if not raw_name:
            continue
        norm = _normalize_location_name(raw_name)
        if not norm:
            continue
        venue = venues_by_norm.get(norm)
        if venue is None:
            venue = CompetitionVenue.objects.create(short_name=raw_name)
            venues_by_norm[norm] = venue
        # Prepare values for varchar -> bigint cast in next AlterField.
        competition.location = str(venue.id)
        competition.save(update_fields=["location"])


def backwards_restore_competition_location_text(apps, schema_editor):
    Competition = apps.get_model("school", "Competition")
    CompetitionVenue = apps.get_model("school", "CompetitionVenue")
    venue_map = {str(item.id): item.short_name for item in CompetitionVenue.objects.all().only("id", "short_name")}
    for competition in Competition.objects.all().only("id", "location").iterator():
        raw_value = (competition.location or "").strip()
        if not raw_value:
            continue
        resolved = venue_map.get(raw_value)
        if resolved:
            competition.location = resolved
            competition.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0046_athletedocument_certificate_status_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(max_length=100, verbose_name="Короткое название"),
                ),
                (
                    "full_address",
                    models.TextField(blank=True, verbose_name="Точный адрес"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Локация соревнований",
                "verbose_name_plural": "Локации соревнований",
                "ordering": ["parent__short_name", "short_name"],
            },
        ),
        migrations.RenameIndex(
            model_name="athletedocument",
            new_name="school_athl_doc_typ_786217_idx",
            old_name="school_athle_doc_typ_0ce5f3_idx",
        ),
        migrations.RenameIndex(
            model_name="athletedocument",
            new_name="school_athl_needs_v_4fdfd0_idx",
            old_name="school_athle_needs_v_d2de15_idx",
        ),
        migrations.AlterField(
            model_name="competition",
            name="birth_year_from",
            field=models.PositiveIntegerField(
                default=school.models.default_birth_year_from,
                help_text="Самый ранний год рождения участников (старшие). Обязательно.",
                verbose_name="Год рождения (с)",
            ),
        ),
        migrations.AddField(
            model_name="competitionvenue",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="school.competitionvenue",
                verbose_name="Родительская локация",
            ),
        ),
        migrations.RunPython(
            code=forwards_fill_competition_venues,
            reverse_code=backwards_restore_competition_location_text,
        ),
        migrations.AlterField(
            model_name="competition",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="school.competitionvenue",
                verbose_name="Место проведения",
            ),
        ),
        migrations.AddIndex(
            model_name="competitionvenue",
            index=models.Index(
                fields=["short_name"], name="school_comp_short_n_eef76e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competitionvenue",
            index=models.Index(
                fields=["parent", "is_active"], name="school_comp_parent__76b9c9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionvenue",
            constraint=models.UniqueConstraint(
                fields=("parent", "short_name"),
                name="uniq_competition_venue_parent_short_name",
            ),
        ),
    ]
