# Generated by Django 6.0.2 on 2026-03-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0047_competitionvenue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionScoringGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название зачетной группы"
                    ),
                ),
                (
                    "gender_scope",
                    models.CharField(
                        choices=[("male", "Мужчины"), ("female", "Женщины")],
                        max_length=16,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "birth_year_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Максимальный год рождения (минимальный возраст).",
                        null=True,
                        verbose_name="Год рождения (от)",
                    ),
                ),
                (
                    "birth_year_to",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Минимальный год рождения. Пусто = и старше.",
                        null=True,
                        verbose_name="Год рождения (до)",
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Дисциплина"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Вручную"), ("ai", "Из AI-документа")],
                        default="manual",
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "source_raw_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Исходная строка AI"
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("parsed", "Распознано"),
                            ("partial", "Распознано частично"),
                            ("unparsed", "Не распознано"),
                        ],
                        default="parsed",
                        max_length=16,
                        verbose_name="Качество распознавания",
                    ),
                ),
                (
                    "parse_comment",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Комментарий распознавания",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_groups",
                        to="school.competition",
                        verbose_name="Соревнование",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scoring_groups",
                        to="school.document",
                        verbose_name="Документ-источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зачетная группа соревнования",
                "verbose_name_plural": "Зачетные группы соревнований",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["competition", "is_active"],
                        name="school_comp_competi_0f2fc0_idx",
                    ),
                    models.Index(
                        fields=["gender_scope", "birth_year_from", "birth_year_to"],
                        name="school_comp_gender__7ea120_idx",
                    ),
                ],
            },
        ),
    ]
