# Generated by Django 6.0.2 on 2026-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0048_competitionscoringgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionscoringgroup",
            name="standard_category",
            field=models.CharField(
                blank=True,
                help_text="Например: U8/U10/U12/U14/U16",
                max_length=8,
                verbose_name="Стандартная категория",
            ),
        ),
        migrations.AddIndex(
            model_name="competitionscoringgroup",
            index=models.Index(
                fields=["competition", "standard_category", "is_active"],
                name="school_comp_competi_2bcd54_idx",
            ),
        ),
    ]
