# Generated by Django 6.0.2 on 2026-03-03 10:11

import re

from django.db import migrations, models


def _normalize_username(raw: str) -> str:
    value = (raw or "").strip()
    if value.startswith("@"):
        value = value[1:]
    return value.lower()


def _parse_telegram(raw: str | None) -> tuple[str, int | None]:
    if not raw:
        return "", None
    value = str(raw).strip()
    deep_link = re.match(r"^tg://user\?id=(\d+)$", value, flags=re.IGNORECASE)
    if deep_link:
        return "", int(deep_link.group(1))

    url_match = re.match(r"^(?:https?://)?t\.me/([\w@+\d_]+)$", value, flags=re.IGNORECASE)
    if url_match:
        value = url_match.group(1)

    if value.startswith("@"):
        value = value[1:]
    if value.isdigit():
        return "", int(value)
    username = _normalize_username(value)
    return (f"https://t.me/{username}" if username else ""), None


def _forward_fill_telegram_id(apps, schema_editor):
    Person = apps.get_model("school", "Person")
    User = apps.get_model("users", "User")

    for person in Person.objects.all().iterator():
        changed_fields: list[str] = []
        normalized_telegram, parsed_tg_id = _parse_telegram(person.telegram)

        if normalized_telegram and person.telegram != normalized_telegram:
            person.telegram = normalized_telegram
            changed_fields.append("telegram")

        if parsed_tg_id and not person.telegram_id:
            person.telegram_id = parsed_tg_id
            changed_fields.append("telegram_id")

        if (not person.telegram_id) and person.telegram:
            username, _ = _parse_telegram(person.telegram)
            if username:
                username_key = username.rsplit("/", 1)[-1]
                user_match = (
                    User.objects
                    .filter(tg_username__iexact=username_key)
                    .exclude(tg_id__isnull=True)
                    .first()
                )
                if user_match:
                    person.telegram_id = user_match.tg_id
                    changed_fields.append("telegram_id")

        if person.telegram_id and not person.telegram:
            user_match = (
                User.objects
                .filter(tg_id=person.telegram_id)
                .exclude(tg_username__isnull=True)
                .exclude(tg_username="")
                .first()
            )
            if user_match:
                person.telegram = f"https://t.me/{_normalize_username(user_match.tg_username)}"
                changed_fields.append("telegram")

        if changed_fields:
            person.save(update_fields=sorted(set(changed_fields)))


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0049_competitionscoringgroup_standard_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.RunPython(_forward_fill_telegram_id, reverse_code=_noop_reverse),
    ]
