# Generated by Django 6.0.2 on 2026-03-03 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
        ("school", "0050_person_telegram_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramparticipant",
            name="linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда связана"
            ),
        ),
        migrations.AddField(
            model_name="telegramparticipant",
            name="linked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_telegram_participants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем связана",
            ),
        ),
        migrations.AddField(
            model_name="telegramparticipant",
            name="linked_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_participant_links",
                to="school.person",
                verbose_name="Связанная персона",
            ),
        ),
        migrations.AddField(
            model_name="telegramparticipant",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
        ),
        migrations.AddIndex(
            model_name="telegramparticipant",
            index=models.Index(fields=["user_id"], name="bot_tp_user_id_idx"),
        ),
    ]
