"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from celery.schedules import crontab


load_dotenv(override=True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG") == "True" else False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "storages",
    "django_filters",
    "corsheaders",
    "school",
    "api",
    "members",
    "classes",
    "groups",
    "users",
    "notifications",
    "bot",
    "whatsapp",
    "assistant",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("NAME"),
        "USER": os.getenv("USER"),
        "PASSWORD": os.getenv("PASSWORD"),
        "HOST": os.getenv("HOST"),
        "PORT": os.getenv("PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Настройки отправки почты для mail.ru
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mail.ru"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = os.getenv("MEDIA_URL", "media/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

def require_setting(name: str) -> str:
    """Возвращает обязательную переменную окружения или поднимает исключение."""
    value = os.getenv(name)
    if not value:
        raise ImproperlyConfigured(f"{name} environment variable must be set")
    return value


# Хранилище файлов: локально (по умолчанию) или S3-совместимое (Yandex Object Storage)
STORAGE_BACKEND = os.getenv("STORAGE_BACKEND", "filesystem").lower()

if STORAGE_BACKEND == "s3":
    AWS_ACCESS_KEY_ID = require_setting("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = require_setting("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = require_setting("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True  # presigned URL’ы для приватных объектов
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}

    custom_domain = os.getenv("AWS_S3_CUSTOM_DOMAIN")
    if custom_domain:
        MEDIA_URL = f"https://{custom_domain.rstrip('/')}/"
    else:
        # если задан endpoint напрямую (например https://storage.yandexcloud.net)
        base = AWS_S3_ENDPOINT_URL.rstrip("/") if AWS_S3_ENDPOINT_URL else ""
        MEDIA_URL = f"{base}/{AWS_STORAGE_BUCKET_NAME}/"

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    # filesystem по умолчанию
    if not MEDIA_URL.startswith("/"):
        MEDIA_URL = "/" + MEDIA_URL
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }


# Настройки для телеграмма
BOT_NAME = os.getenv("BOT_NAME")
BOT_TOKEN = os.getenv("BOT_TOKEN")
SITE_BASE_URL = require_setting("SITE_BASE_URL").rstrip("/")
TELEGRAM_LOG_CHAT_ID = os.getenv("TELEGRAM_LOG_CHAT_ID")
TELEGRAM_ADMIN_IDS = [
    admin_id.strip()
    for admin_id in os.getenv("TELEGRAM_ADMIN_IDS", TELEGRAM_LOG_CHAT_ID or "").split(",")
    if admin_id.strip()
]

TELEGRAM_COACH_IDS = [
    coach_id.strip()
    for coach_id in os.getenv("TELEGRAM_COACH_IDS", "").split(",")
    if coach_id.strip()
]

TELEGRAM_MANAGER_IDS = [
    manager_id.strip()
    for manager_id in os.getenv("TELEGRAM_MANAGER_IDS", "").split(",")
    if manager_id.strip()
]
TELEGRAM_DOC_IMPORT_ENABLED = os.getenv("TELEGRAM_DOC_IMPORT_ENABLED", "False") == "True"
TELEGRAM_DOC_IMPORT_CHAT_IDS = [
    int(chat_id.strip())
    for chat_id in os.getenv("TELEGRAM_DOC_IMPORT_CHAT_IDS", "").split(",")
    if chat_id.strip().lstrip("-").isdigit()
]
_telegram_doc_ext = [
    ext.strip().lower().lstrip(".")
    for ext in os.getenv("TELEGRAM_DOC_IMPORT_ALLOWED_EXTENSIONS", "pdf,doc,docx").split(",")
    if ext.strip()
]
TELEGRAM_DOC_IMPORT_ALLOWED_EXTENSIONS = tuple(_telegram_doc_ext or ["pdf", "doc", "docx"])
TELEGRAM_DOC_IMPORT_MAX_SIZE_MB = int(os.getenv("TELEGRAM_DOC_IMPORT_MAX_SIZE_MB", "20"))
TELEGRAM_DOC_IMPORT_DEDUPLICATE = os.getenv("TELEGRAM_DOC_IMPORT_DEDUPLICATE", "True") == "True"
TELEGRAM_DOC_IMPORT_HTTP_TIMEOUT_SEC = float(os.getenv("TELEGRAM_DOC_IMPORT_HTTP_TIMEOUT_SEC", "30"))
ONLINE_RESULTS_WEBHOOK_SECRET = os.getenv("ONLINE_RESULTS_WEBHOOK_SECRET", "")
ONLINE_RESULTS_WEBHOOK_PUBLIC_BASE_URL = os.getenv("ONLINE_RESULTS_WEBHOOK_PUBLIC_BASE_URL", "").strip()
ONLINE_RESULTS_STREAM_START_URL = os.getenv(
    "ONLINE_RESULTS_STREAM_START_URL",
    "http://localhost:8002/v1/streams",
)
ONLINE_RESULTS_STREAM_STOP_URL_TEMPLATE = os.getenv(
    "ONLINE_RESULTS_STREAM_STOP_URL_TEMPLATE",
    "",
).strip()
ONLINE_RESULTS_STREAM_TIMEOUT_SEC = int(os.getenv("ONLINE_RESULTS_STREAM_TIMEOUT_SEC", "15"))
ONLINE_RESULTS_STREAM_AUTH_TOKEN = os.getenv("ONLINE_RESULTS_STREAM_AUTH_TOKEN", "")
ONLINE_RESULTS_STREAM_POLL_INTERVAL_SEC = float(
    os.getenv("ONLINE_RESULTS_STREAM_POLL_INTERVAL_SEC", "1.0")
)
ONLINE_RESULTS_STREAM_REFRESH_TITLES_EVERY = int(
    os.getenv("ONLINE_RESULTS_STREAM_REFRESH_TITLES_EVERY", "120")
)
ONLINE_RESULTS_STREAM_FINALIZE_TIMEOUT_SEC = int(
    os.getenv("ONLINE_RESULTS_STREAM_FINALIZE_TIMEOUT_SEC", "300")
)
ONLINE_RESULTS_STREAM_FINALIZE_MAX_MISSING = int(
    os.getenv("ONLINE_RESULTS_STREAM_FINALIZE_MAX_MISSING", "2")
)
ONLINE_RESULTS_STREAM_WORKER_PRINT = (
    os.getenv("ONLINE_RESULTS_STREAM_WORKER_PRINT", "False") == "True"
)
ONLINE_RESULTS_STREAM_RESUME_STALE_SEC = int(
    os.getenv("ONLINE_RESULTS_STREAM_RESUME_STALE_SEC", "180")
)
ONLINE_RESULTS_STREAM_PENDING_TIMEOUT_SEC = int(
    os.getenv("ONLINE_RESULTS_STREAM_PENDING_TIMEOUT_SEC", "45")
)

LOGIN_URL = "users:login_page"
LOGIN_REDIRECT_URL = "school:index"
LOGOUT_REDIRECT_URL = "users:login_page"

def _to_origin(url: str) -> str:
    parsed = urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        raise ImproperlyConfigured(f"Некорректный URL для origins: {url}")
    return f"{parsed.scheme}://{parsed.netloc}"


raw_origins = os.getenv("CORS_ALLOWED_ORIGINS")
if raw_origins:
    CORS_ALLOWED_ORIGINS = [_to_origin(origin.strip()) for origin in raw_origins.split(",") if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [_to_origin(SITE_BASE_URL)]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"
SESSION_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"


LOG_DIR = Path(os.getenv("LOG_DIR", BASE_DIR / "logs"))
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    pass
DJANGO_LOG_FILE = LOG_DIR / "django.log"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "standard",
            "filename": str(DJANGO_LOG_FILE),
            "when": "midnight",
            "backupCount": 7,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "auth.telegram": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "bot.telegram": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if BOT_TOKEN and TELEGRAM_LOG_CHAT_ID:
    LOGGING["handlers"]["telegram"] = {
        "level": "ERROR",
        "class": "config.logging_handlers.TelegramLogHandler",
        "chat_id": TELEGRAM_LOG_CHAT_ID,
        "formatter": "standard",
    }
    LOGGING["loggers"]["django"]["handlers"].append("telegram")
    LOGGING["loggers"]["auth.telegram"]["handlers"].append("telegram")
    LOGGING["loggers"]["bot.telegram"]["handlers"].append("telegram")


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_BEAT_SCHEDULE = {
    "ensure-monthly-contract-services": {
        "task": "school.tasks.ensure_monthly_contract_services",
        "schedule": crontab(hour=3, minute=0),
    },
    "notify-coach-today-trainings": {
        "task": "classes.tasks.notify_today_trainings_task",
        "schedule": crontab(hour=10, minute=0),
    },
    "notify-coach-tomorrow-trainings": {
        "task": "classes.tasks.notify_tomorrow_trainings_task",
        "schedule": crontab(hour=10, minute=5),
    },
    "ensure-weekly-template-schedule": {
        "task": "classes.tasks.ensure_weekly_schedule_task",
        "schedule": crontab(hour=10, minute=10),
    },
    "send-training-reminders-daily": {
        "task": "classes.tasks.send_training_reminders_task",
        "schedule": crontab(hour=10, minute=30),
    },
    "notify-pending-users-daily": {
        "task": "users.tasks.notify_pending_users_daily_task",
        "schedule": crontab(hour=12, minute=0),
    },
    "notify-bot-activity-daily": {
        "task": "users.tasks.notify_bot_activity_daily_task",
        "schedule": crontab(hour=23, minute=0),
    },
    "assistant-sync-members-daily": {
        "task": "assistant.tasks.send_members_snapshot_task",
        "schedule": crontab(hour=3, minute=0),
    },
    "assistant-sync-taxonomy-daily": {
        "task": "assistant.tasks.send_taxonomy_snapshot_task",
        "schedule": crontab(hour=3, minute=2),
    },
    "assistant-sync-trainings-daily": {
        "task": "assistant.tasks.send_upcoming_trainings_snapshot_task",
        "schedule": crontab(hour=3, minute=4),
    },
    "reconcile-athlete-certificate-validity-daily": {
        "task": "school.tasks.reconcile_athlete_certificate_validity",
        "schedule": crontab(hour=3, minute=6),
    },
    "docs-ai-orchestrator": {
        "task": "school.tasks.enqueue_documents_for_ai_analysis",
        "schedule": crontab(minute="*/30"),
        "options": {"queue": os.getenv("CELERY_QUEUE_DOCS_ANALYSIS", "docs_analysis")},
    },
}

DOCS_ANALYZER_URL = os.getenv("DOCS_ANALYZER_URL", "http://192.168.0.4:8001")
DOCS_ANALYZER_TIMEOUT_SEC = float(os.getenv("DOCS_ANALYZER_TIMEOUT_SEC", "30"))
DOCS_ANALYZER_BATCH_SIZE = int(os.getenv("DOCS_ANALYZER_BATCH_SIZE", "3"))
DOCS_ANALYZER_CONCURRENCY = int(os.getenv("DOCS_ANALYZER_CONCURRENCY", "2"))
DOCS_ANALYZER_MAX_URLS = int(os.getenv("DOCS_ANALYZER_MAX_URLS", "3"))
DOCS_ANALYZER_SIGNED_URL_TTL_SEC = int(os.getenv("DOCS_ANALYZER_SIGNED_URL_TTL_SEC", "300"))
DOCS_ANALYZER_RETRY_MAX = int(os.getenv("DOCS_ANALYZER_RETRY_MAX", "1"))
DOCS_ANALYZER_RETRY_BACKOFF_SEC = int(os.getenv("DOCS_ANALYZER_RETRY_BACKOFF_SEC", "15"))
DOCS_ANALYZER_RETRY_JITTER_SEC = int(os.getenv("DOCS_ANALYZER_RETRY_JITTER_SEC", "5"))
DOCS_ANALYZER_TASK_RATE_LIMIT = os.getenv("DOCS_ANALYZER_TASK_RATE_LIMIT", "10/m")
DOCS_ANALYZER_DOCS_PER_MIN_LIMIT = int(os.getenv("DOCS_ANALYZER_DOCS_PER_MIN_LIMIT", "120"))
DOCS_ANALYZER_TOKENS_PER_MIN_LIMIT = int(os.getenv("DOCS_ANALYZER_TOKENS_PER_MIN_LIMIT", "0"))
DOCS_ANALYZER_TOKENS_PER_DOC_ESTIMATE = int(os.getenv("DOCS_ANALYZER_TOKENS_PER_DOC_ESTIMATE", "3000"))
DOCS_ANALYZER_BUDGET_BACKOFF_SEC = int(os.getenv("DOCS_ANALYZER_BUDGET_BACKOFF_SEC", "20"))
DOCS_ANALYZER_BUDGET_BACKOFF_JITTER_SEC = int(os.getenv("DOCS_ANALYZER_BUDGET_BACKOFF_JITTER_SEC", "5"))
CELERY_QUEUE_DOCS_ANALYSIS = os.getenv("CELERY_QUEUE_DOCS_ANALYSIS", "docs_analysis")
DOCS_STORAGE_SYNC_PREFIX = os.getenv("DOCS_STORAGE_SYNC_PREFIX", "documents")
DOCS_SYNC_ON_STARTUP = os.getenv("DOCS_SYNC_ON_STARTUP", "False") == "True"
DOCS_SYNC_STARTUP_COOLDOWN_SEC = int(os.getenv("DOCS_SYNC_STARTUP_COOLDOWN_SEC", "180"))
DOCS_BULK_UPLOAD_CHUNK_SIZE = int(os.getenv("DOCS_BULK_UPLOAD_CHUNK_SIZE", "20"))
DOCS_AI_ORCHESTRATOR_ENABLED = os.getenv("DOCS_AI_ORCHESTRATOR_ENABLED", "False") == "True"
CELERY_TASK_ACKS_LATE = os.getenv("CELERY_TASK_ACKS_LATE", "True") == "True"
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1"))
CELERY_TASK_REJECT_ON_WORKER_LOST = os.getenv("CELERY_TASK_REJECT_ON_WORKER_LOST", "True") == "True"
CELERY_TASK_ROUTES = {
    "school.tasks.enqueue_documents_for_ai_analysis": {"queue": CELERY_QUEUE_DOCS_ANALYSIS},
    "school.tasks.analyze_documents_batch_task": {"queue": CELERY_QUEUE_DOCS_ANALYSIS},
    "school.tasks.sync_documents_from_storage_task": {"queue": CELERY_QUEUE_DOCS_ANALYSIS},
    "bot.tasks.process_telegram_document_task": {"queue": "celery"},
}
CELERY_TASK_ANNOTATIONS = {
    "school.tasks.analyze_documents_batch_task": {"rate_limit": DOCS_ANALYZER_TASK_RATE_LIMIT},
}

if not DOCS_AI_ORCHESTRATOR_ENABLED:
    CELERY_BEAT_SCHEDULE.pop("docs-ai-orchestrator", None)

AI_ASSISTANT_ENABLED = os.getenv("AI_ASSISTANT_ENABLED", "False") == "True"
AI_ASSISTANT_BASE_URL = os.getenv("AI_ASSISTANT_BASE_URL", "http://109.207.171.231")

# Redis для сервисных токенов (автологин между браузерами)
REDIS_XFER_URL = os.getenv("REDIS_XFER_URL", os.getenv("REDIS_URL", "redis://localhost:6379/1"))
XFER_TOKEN_TTL_SECONDS = int(os.getenv("XFER_TOKEN_TTL_SECONDS", "600"))
XFER_TOKEN_POST_USE_TTL_SECONDS = int(os.getenv("XFER_TOKEN_POST_USE_TTL_SECONDS", "60"))
AI_ASSISTANT_TIMEOUT = float(os.getenv("AI_ASSISTANT_TIMEOUT", "10"))
AI_ASSISTANT_SERVICE_ACCOUNT_SLUG = os.getenv("AI_ASSISTANT_SERVICE_ACCOUNT_SLUG", "ai-assistant")
AI_ASSISTANT_ENDPOINT_MEMBERS = os.getenv("AI_ASSISTANT_ENDPOINT_MEMBERS", "/api/v1/sync/members/")
AI_ASSISTANT_ENDPOINT_TAXONOMY = os.getenv("AI_ASSISTANT_ENDPOINT_TAXONOMY", "/api/v1/sync/taxonomy/")
AI_ASSISTANT_ENDPOINT_TRAININGS = os.getenv("AI_ASSISTANT_ENDPOINT_TRAININGS", "/api/v1/sync/trainings/")
