"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from celery.schedules import crontab


load_dotenv(override=True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG") == "True" else False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "school",
    "members",
    "classes",
    "groups",
    "users",
    "notifications",
    "bot",
    "whatsapp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("NAME"),
        "USER": os.getenv("USER"),
        "PASSWORD": os.getenv("PASSWORD"),
        "HOST": os.getenv("HOST"),
        "PORT": os.getenv("PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Настройки отправки почты для mail.ru
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mail.ru"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

def require_setting(name: str) -> str:
    """Возвращает обязательную переменную окружения или поднимает исключение."""
    value = os.getenv(name)
    if not value:
        raise ImproperlyConfigured(f"{name} environment variable must be set")
    return value


# Настройки для телеграмма
BOT_NAME = os.getenv("BOT_NAME")
BOT_TOKEN = os.getenv("BOT_TOKEN")
SITE_BASE_URL = require_setting("SITE_BASE_URL").rstrip("/")
TELEGRAM_LOG_CHAT_ID = os.getenv("TELEGRAM_LOG_CHAT_ID")
TELEGRAM_ADMIN_IDS = [
    admin_id.strip()
    for admin_id in os.getenv("TELEGRAM_ADMIN_IDS", TELEGRAM_LOG_CHAT_ID or "").split(",")
    if admin_id.strip()
]

TELEGRAM_COACH_IDS = [
    coach_id.strip()
    for coach_id in os.getenv("TELEGRAM_COACH_IDS", "").split(",")
    if coach_id.strip()
]

LOGIN_URL = "users:login_page"
LOGIN_REDIRECT_URL = "school:index"
LOGOUT_REDIRECT_URL = "users:login_page"

def _to_origin(url: str) -> str:
    parsed = urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        raise ImproperlyConfigured(f"Некорректный URL для origins: {url}")
    return f"{parsed.scheme}://{parsed.netloc}"


raw_origins = os.getenv("CORS_ALLOWED_ORIGINS")
if raw_origins:
    CORS_ALLOWED_ORIGINS = [_to_origin(origin.strip()) for origin in raw_origins.split(",") if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [_to_origin(SITE_BASE_URL)]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"
SESSION_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "auth.telegram": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "bot.telegram": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if BOT_TOKEN and TELEGRAM_LOG_CHAT_ID:
    LOGGING["handlers"]["telegram"] = {
        "level": "INFO",
        "class": "config.logging_handlers.TelegramLogHandler",
        "chat_id": TELEGRAM_LOG_CHAT_ID,
        "formatter": "standard",
    }
    LOGGING["loggers"]["django"]["handlers"].append("telegram")
    LOGGING["loggers"]["auth.telegram"]["handlers"].append("telegram")
    LOGGING["loggers"]["bot.telegram"]["handlers"].append("telegram")


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_BEAT_SCHEDULE = {
    "ensure-monthly-contract-services": {
        "task": "school.tasks.ensure_monthly_contract_services",
        "schedule": crontab(hour=3, minute=0),
    },
    "notify-coach-today-trainings": {
        "task": "classes.tasks.notify_today_trainings_task",
        "schedule": crontab(hour=10, minute=0),
    },
    "notify-coach-tomorrow-trainings": {
        "task": "classes.tasks.notify_tomorrow_trainings_task",
        "schedule": crontab(hour=10, minute=5),
    },
    "ensure-weekly-template-schedule": {
        "task": "classes.tasks.ensure_weekly_schedule_task",
        "schedule": crontab(hour=10, minute=10),
    },
}
